/* 사원정보 */
CREATE TABLE EMP (
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	EMP_NAME VARCHAR2(50) NOT NULL, /* 사원이름 */
	EMP_ENAME VARCHAR2(50) NOT NULL, /* 사원영어이름 */
	EMP_PWD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	EMP_TEL VARCHAR2(50) NOT NULL, /* 전화번호 */
	EMP_SSN VARCHAR2(50) NOT NULL, /* 주민번호 */
	EMP_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
	EMP_ZIPCODE VARCHAR2(50) NOT NULL, /* 우편번호 */
	EMP_ADDR VARCHAR2(200) NOT NULL, /* 주소 */
	EMP_ADDR2 VARCHAR2(200) NOT NULL, /* 상세주소 */
	EMP_HIREDATE TIMESTAMP NOT NULL, /* 입사일 */
	EMP_HOBBY VARCHAR2(50), /* 취미 */
	EMP_SCHOOL VARCHAR2(50) NOT NULL, /* 출신학교 */
	EMP_MAJOR VARCHAR2(50) NOT NULL, /* 전공 */
	EMP_OUTDATE TIMESTAMP, /* 퇴사일 */
	EMP_IMG VARCHAR2(100) NOT NULL, /* 사원사진 */
	EMP_LEV VARCHAR2(50) NOT NULL, /* 권한 */
	EMP_SAL NUMBER NOT NULL, /* 봉급 */
	EMP_BOOKMARK VARCHAR2(200), /* 즐겨찾기 */
	DEPT_NO NUMBER NOT NULL, /* 부서코드 */
	EMP_POSITION VARCHAR2(30) /* 직급 */
);

COMMENT ON TABLE EMP IS '사원정보';

COMMENT ON COLUMN EMP.EMP_NO IS '사원번호';

COMMENT ON COLUMN EMP.EMP_NAME IS '사원이름';

COMMENT ON COLUMN EMP.EMP_ENAME IS '사원영어이름';

COMMENT ON COLUMN EMP.EMP_PWD IS '비밀번호';

COMMENT ON COLUMN EMP.EMP_TEL IS '전화번호';

COMMENT ON COLUMN EMP.EMP_SSN IS '주민번호';

COMMENT ON COLUMN EMP.EMP_EMAIL IS '이메일';

COMMENT ON COLUMN EMP.EMP_ZIPCODE IS '우편번호';

COMMENT ON COLUMN EMP.EMP_ADDR IS '주소';

COMMENT ON COLUMN EMP.EMP_ADDR2 IS '상세주소';

COMMENT ON COLUMN EMP.EMP_HIREDATE IS '입사일';

COMMENT ON COLUMN EMP.EMP_HOBBY IS '취미';

COMMENT ON COLUMN EMP.EMP_SCHOOL IS '출신학교';

COMMENT ON COLUMN EMP.EMP_MAJOR IS '전공';

COMMENT ON COLUMN EMP.EMP_OUTDATE IS '퇴사일';

COMMENT ON COLUMN EMP.EMP_IMG IS '사원사진';

COMMENT ON COLUMN EMP.EMP_LEV IS '권한';

COMMENT ON COLUMN EMP.EMP_SAL IS '봉급';

COMMENT ON COLUMN EMP.EMP_BOOKMARK IS '즐겨찾기';

COMMENT ON COLUMN EMP.DEPT_NO IS '부서코드';

COMMENT ON COLUMN EMP.EMP_POSITION IS '직급';

CREATE UNIQUE INDEX PK_EMP
	ON EMP (
		EMP_NO ASC
	);

ALTER TABLE EMP
	ADD
		CONSTRAINT PK_EMP
		PRIMARY KEY (
			EMP_NO
		);

/* 부서테이블 */
CREATE TABLE DEPT (
	DEPT_NO NUMBER NOT NULL, /* 부서코드 */
	DEMPT_NAME VARCHAR2(100) NOT NULL /* 부서명 */
);

COMMENT ON TABLE DEPT IS '부서테이블';

COMMENT ON COLUMN DEPT.DEPT_NO IS '부서코드';

COMMENT ON COLUMN DEPT.DEMPT_NAME IS '부서명';

CREATE UNIQUE INDEX PK_DEPT
	ON DEPT (
		DEPT_NO ASC
	);

ALTER TABLE DEPT
	ADD
		CONSTRAINT PK_DEPT
		PRIMARY KEY (
			DEPT_NO
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTI_NO NUMBER NOT NULL, /* 공지사항게시글번호 */
	NOTI_TITLE VARCHAR2(200) NOT NULL, /* 글제목 */
	EMP_NO NUMBER NOT NULL, /* 글쓴이 */
	NOTI_CONTENT CLOB NOT NULL, /* 글내용 */
	NOTI_REGDATE TIMESTAMP DEFAULT sysdate, /* 등록일 */
	NOTI_FILENAME VARCHAR2(500), /* 업로드파일명 */
	NOTI_FILESIZE VARCHAR2(50), /* 파일사이즈 */
	NOTI_OFILENAME VARCHAR2(500), /* 변경전 업로드 파일명 */
	NOTI_DOWNCNT NUMBER DEFAULT 0, /* 다운수 */
	NOTI_READCNT NUMBER DEFAULT 0 /* 조회수 */
);

COMMENT ON TABLE NOTICE IS '공지사항';

COMMENT ON COLUMN NOTICE.NOTI_NO IS '공지사항게시글번호';

COMMENT ON COLUMN NOTICE.NOTI_TITLE IS '글제목';

COMMENT ON COLUMN NOTICE.EMP_NO IS '글쓴이';

COMMENT ON COLUMN NOTICE.NOTI_CONTENT IS '글내용';

COMMENT ON COLUMN NOTICE.NOTI_REGDATE IS '등록일';

COMMENT ON COLUMN NOTICE.NOTI_FILENAME IS '업로드파일명';

COMMENT ON COLUMN NOTICE.NOTI_FILESIZE IS '파일사이즈';

COMMENT ON COLUMN NOTICE.NOTI_OFILENAME IS '변경전 업로드 파일명';

COMMENT ON COLUMN NOTICE.NOTI_DOWNCNT IS '다운수';

COMMENT ON COLUMN NOTICE.NOTI_READCNT IS '조회수';

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTI_NO ASC
	);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTI_NO
		);

/* 자원관리테이블 */
CREATE TABLE RESOURCEREG (
	RES_NO NUMBER NOT NULL, /* 자원번호 */
	RES_CATEG VARCHAR2(50) NOT NULL, /* 자원대분류 */
	RES_NAME VARCHAR2(50) NOT NULL, /* 자원명 */
	RES_DESC VARCHAR2(1000), /* 자원설명 */
	RES_REGDATE TIMESTAMP DEFAULT sysdate, /* 자원등록일 */
	EMP_NO NUMBER NOT NULL /* 자원관리자 */
);

COMMENT ON TABLE RESOURCEREG IS '자원관리테이블';

COMMENT ON COLUMN RESOURCEREG.RES_NO IS '자원번호';

COMMENT ON COLUMN RESOURCEREG.RES_CATEG IS '자원대분류';

COMMENT ON COLUMN RESOURCEREG.RES_NAME IS '자원명';

COMMENT ON COLUMN RESOURCEREG.RES_DESC IS '자원설명';

COMMENT ON COLUMN RESOURCEREG.RES_REGDATE IS '자원등록일';

COMMENT ON COLUMN RESOURCEREG.EMP_NO IS '자원관리자';

CREATE UNIQUE INDEX PK_RESOURCEREG
	ON RESOURCEREG (
		RES_NO ASC
	);

ALTER TABLE RESOURCEREG
	ADD
		CONSTRAINT PK_RESOURCEREG
		PRIMARY KEY (
			RES_NO
		);

/* 웹하드 */
CREATE TABLE WEBHARD (
	COL NUMBER NOT NULL, /* 웹하드게시글번호 */
	EMP_NO NUMBER NOT NULL, /* 글쓴이 */
	WEB_TITLE VARCHAR2(200) NOT NULL, /* 글제목 */
	WEB_CONTENT CLOB NOT NULL, /* 글내용 */
	WEB_REGDATE TIMESTAMP DEFAULT sysdate, /* 등록일 */
	WEB_FILENAME VARCHAR2(500) NOT NULL, /* 업로드파일명 */
	WEB_FILESIZE VARCHAR2(50) NOT NULL, /* 파일사이즈 */
	WEB_OFILENAME VARCHAR2(500) NOT NULL, /* 변경전 업로드파일명 */
	WEB_DOWNCNT NUMBER DEFAULT 0, /* 다운수 */
	WEB_READCNT NUMBER DEFAULT 0 /* 조회수 */
);

COMMENT ON TABLE WEBHARD IS '웹하드';

COMMENT ON COLUMN WEBHARD.COL IS '웹하드게시글번호';

COMMENT ON COLUMN WEBHARD.EMP_NO IS '글쓴이';

COMMENT ON COLUMN WEBHARD.WEB_TITLE IS '글제목';

COMMENT ON COLUMN WEBHARD.WEB_CONTENT IS '글내용';

COMMENT ON COLUMN WEBHARD.WEB_REGDATE IS '등록일';

COMMENT ON COLUMN WEBHARD.WEB_FILENAME IS '업로드파일명';

COMMENT ON COLUMN WEBHARD.WEB_FILESIZE IS '파일사이즈';

COMMENT ON COLUMN WEBHARD.WEB_OFILENAME IS '변경전 업로드파일명';

COMMENT ON COLUMN WEBHARD.WEB_DOWNCNT IS '다운수';

COMMENT ON COLUMN WEBHARD.WEB_READCNT IS '조회수';

CREATE UNIQUE INDEX PK_WEBHARD
	ON WEBHARD (
		COL ASC
	);

ALTER TABLE WEBHARD
	ADD
		CONSTRAINT PK_WEBHARD
		PRIMARY KEY (
			COL
		);

/* 쪽지함 */
CREATE TABLE MESSAGE (
	MSG_NO NUMBER NOT NULL, /* 쪽지번호 */
	MSG_TITLE VARCHAR2(200) NOT NULL, /* 쪽지제목 */
	MSG_CONTENT CLOB NOT NULL, /* 쪽지내용 */
	MSG_IMPFLAG VARCHAR2(50) NOT NULL, /* 중요쪽지여부 */
	MSG_REGDATE TIMESTAMP DEFAULT sysdate, /* 날짜 */
	SENDEMP_NO NUMBER NOT NULL /* 보낸회원번호 */
);

COMMENT ON TABLE MESSAGE IS '쪽지함';

COMMENT ON COLUMN MESSAGE.MSG_NO IS '쪽지번호';

COMMENT ON COLUMN MESSAGE.MSG_TITLE IS '쪽지제목';

COMMENT ON COLUMN MESSAGE.MSG_CONTENT IS '쪽지내용';

COMMENT ON COLUMN MESSAGE.MSG_IMPFLAG IS '중요쪽지여부';

COMMENT ON COLUMN MESSAGE.MSG_REGDATE IS '날짜';

COMMENT ON COLUMN MESSAGE.SENDEMP_NO IS '보낸회원번호';

CREATE UNIQUE INDEX PK_MESSAGE
	ON MESSAGE (
		MSG_NO ASC
	);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT PK_MESSAGE
		PRIMARY KEY (
			MSG_NO
		);

/* 사내뉴스게시판 */
CREATE TABLE NEWS (
	NEWS_NO NUMBER NOT NULL, /* 게시글번호 */
	NEWS_TITLE VARCHAR2(500) NOT NULL, /* 글제목 */
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	NEWS_CONTENT CLOB NOT NULL, /* 글내용 */
	NEWS_REGDATE TIMESTAMP DEFAULT sysdate, /* 등록일 */
	NEWS_IMAGE VARCHAR2(200), /* 이미지이름 */
	NEWS_READCNT NUMBER DEFAULT 0, /* 조회수 */
	NEWS_LIKE NUMBER DEFAULT 0 /* 추천 */
);

COMMENT ON TABLE NEWS IS '사내뉴스게시판';

COMMENT ON COLUMN NEWS.NEWS_NO IS '게시글번호';

COMMENT ON COLUMN NEWS.NEWS_TITLE IS '글제목';

COMMENT ON COLUMN NEWS.EMP_NO IS '사원번호';

COMMENT ON COLUMN NEWS.NEWS_CONTENT IS '글내용';

COMMENT ON COLUMN NEWS.NEWS_REGDATE IS '등록일';

COMMENT ON COLUMN NEWS.NEWS_IMAGE IS '이미지이름';

COMMENT ON COLUMN NEWS.NEWS_READCNT IS '조회수';

COMMENT ON COLUMN NEWS.NEWS_LIKE IS '추천';

CREATE UNIQUE INDEX PK_NEWS
	ON NEWS (
		NEWS_NO ASC
	);

ALTER TABLE NEWS
	ADD
		CONSTRAINT PK_NEWS
		PRIMARY KEY (
			NEWS_NO
		);

/* 사내뉴스게시판 답변 */
CREATE TABLE NEWS_COM (
	COM_NO NUMBER NOT NULL, /* 답글번호 */
	NEWS_NO NUMBER NOT NULL, /* 게시글번호 */
	EMP_NO NUMBER NOT NULL, /* 작성자 */
	COM_CONTENT VARCHAR2(2000) NOT NULL, /* 내용 */
	COM_REGDATE TIMESTAMP DEFAULT sysdate, /* 작성일 */
	COM_LIKE NUMBER DEFAULT 0 /* 추천 */
);

COMMENT ON TABLE NEWS_COM IS '사내뉴스게시판 답변';

COMMENT ON COLUMN NEWS_COM.COM_NO IS '답글번호';

COMMENT ON COLUMN NEWS_COM.NEWS_NO IS '게시글번호';

COMMENT ON COLUMN NEWS_COM.EMP_NO IS '작성자';

COMMENT ON COLUMN NEWS_COM.COM_CONTENT IS '내용';

COMMENT ON COLUMN NEWS_COM.COM_REGDATE IS '작성일';

COMMENT ON COLUMN NEWS_COM.COM_LIKE IS '추천';

CREATE UNIQUE INDEX PK_NEWS_COM
	ON NEWS_COM (
		COM_NO ASC
	);

ALTER TABLE NEWS_COM
	ADD
		CONSTRAINT PK_NEWS_COM
		PRIMARY KEY (
			COM_NO
		);

/* 주소록(개인즐겨찾기) */
CREATE TABLE ADDRBOOK (
	ADDR_NO NUMBER NOT NULL, /* 주소록번호 */
	ADDR_NAME VARCHAR2(500) NOT NULL, /* 주소록이름 */
	ADDR_COMP VARCHAR2(200), /* 회사명 */
	ADDR_TEL VARCHAR2(50) NOT NULL, /* 전화번호 */
	ADDR_EMAIL VARCHAR2(100), /* 이메일 */
	ADDR_POSI VARCHAR2(50), /* 직급 */
	ADDR_ISDEL VARCHAR2(50), /* 삭제여부 */
	EMP_NO NUMBER NOT NULL /* 사원번호 */
);

COMMENT ON TABLE ADDRBOOK IS '주소록(개인즐겨찾기)';

COMMENT ON COLUMN ADDRBOOK.ADDR_NO IS '주소록번호';

COMMENT ON COLUMN ADDRBOOK.ADDR_NAME IS '주소록이름';

COMMENT ON COLUMN ADDRBOOK.ADDR_COMP IS '회사명';

COMMENT ON COLUMN ADDRBOOK.ADDR_TEL IS '전화번호';

COMMENT ON COLUMN ADDRBOOK.ADDR_EMAIL IS '이메일';

COMMENT ON COLUMN ADDRBOOK.ADDR_POSI IS '직급';

COMMENT ON COLUMN ADDRBOOK.ADDR_ISDEL IS '삭제여부';

COMMENT ON COLUMN ADDRBOOK.EMP_NO IS '사원번호';

CREATE UNIQUE INDEX PK_ADDRBOOK
	ON ADDRBOOK (
		ADDR_NO ASC
	);

ALTER TABLE ADDRBOOK
	ADD
		CONSTRAINT PK_ADDRBOOK
		PRIMARY KEY (
			ADDR_NO
		);

/* 개인스케쥴러 */
CREATE TABLE PSCHEDULE (
	PSCH_NO NUMBER NOT NULL, /* 개인 스케쥴번호 */
	PSCH_TITLE VARCHAR2(200) NOT NULL, /* 개인 스케쥴제목 */
	PSCH_START TIMESTAMP NOT NULL, /* 개인 스케쥴시작날짜 */
	PSCH_END TIMESTAMP NOT NULL, /* 개인 스케쥴끝날짜 */
	PSCH_CONTENT VARCHAR2(1000) NOT NULL, /* 개인 스케쥴내용 */
	PSCH_CATEG VARCHAR2(50) NOT NULL, /* 개인 스케쥴대분류 */
	EMP_NO NUMBER NOT NULL /* 사원번호 */
);

COMMENT ON TABLE PSCHEDULE IS '개인스케쥴러';

COMMENT ON COLUMN PSCHEDULE.PSCH_NO IS '개인 스케쥴번호';

COMMENT ON COLUMN PSCHEDULE.PSCH_TITLE IS '개인 스케쥴제목';

COMMENT ON COLUMN PSCHEDULE.PSCH_START IS '개인 스케쥴시작날짜';

COMMENT ON COLUMN PSCHEDULE.PSCH_END IS '개인 스케쥴끝날짜';

COMMENT ON COLUMN PSCHEDULE.PSCH_CONTENT IS '개인 스케쥴내용';

COMMENT ON COLUMN PSCHEDULE.PSCH_CATEG IS '개인 스케쥴대분류';

COMMENT ON COLUMN PSCHEDULE.EMP_NO IS '사원번호';

CREATE UNIQUE INDEX PK_PSCHEDULE
	ON PSCHEDULE (
		PSCH_NO ASC
	);

ALTER TABLE PSCHEDULE
	ADD
		CONSTRAINT PK_PSCHEDULE
		PRIMARY KEY (
			PSCH_NO
		);

/* 자원예약테이블 */
CREATE TABLE RESERVATION (
	RV_NO NUMBER NOT NULL, /* 자원예약번호 */
	RES_NO NUMBER NOT NULL, /* 자원번호 */
	RV_START TIMESTAMP NOT NULL, /* 자원예약시작시간 */
	RV_END TIMESTAMP NOT NULL, /* 자원예약종료시간 */
	EMP_NO NUMBER NOT NULL, /* 자원예약자번호 */
	RV_CONTENT VARCHAR2(1000) NOT NULL, /* 자원예약내용 */
	RV_CONFIRM VARCHAR2(50), /* 자원승인여부 */
	RV_REGDATE TIMESTAMP DEFAULT sysdate /* 자원예약일 */
);

COMMENT ON TABLE RESERVATION IS '자원예약테이블';

COMMENT ON COLUMN RESERVATION.RV_NO IS '자원예약번호';

COMMENT ON COLUMN RESERVATION.RES_NO IS '자원번호';

COMMENT ON COLUMN RESERVATION.RV_START IS '자원예약시작시간';

COMMENT ON COLUMN RESERVATION.RV_END IS '자원예약종료시간';

COMMENT ON COLUMN RESERVATION.EMP_NO IS '자원예약자번호';

COMMENT ON COLUMN RESERVATION.RV_CONTENT IS '자원예약내용';

COMMENT ON COLUMN RESERVATION.RV_CONFIRM IS '자원승인여부';

COMMENT ON COLUMN RESERVATION.RV_REGDATE IS '자원예약일';

CREATE UNIQUE INDEX PK_RESERVATION
	ON RESERVATION (
		RV_NO ASC
	);

ALTER TABLE RESERVATION
	ADD
		CONSTRAINT PK_RESERVATION
		PRIMARY KEY (
			RV_NO
		);

/* 팀내스케쥴러 */
CREATE TABLE TSCHEDULE (
	TSCH_NO NUMBER NOT NULL, /* 팀내 스케쥴번호 */
	TSCH_TITLE VARCHAR2(200) NOT NULL, /* 팀내 스케쥴제목 */
	TSCH_START TIMESTAMP NOT NULL, /* 팀내 스케쥴시작날짜 */
	TSCH_END TIMESTAMP NOT NULL, /* 팀내 스케쥴끝날짜 */
	TSCH_CONTENT VARCHAR2(1000) NOT NULL, /* 팀내 스케쥴내용 */
	TSCH_CATEG VARCHAR2(50) NOT NULL, /* 팀내 스케쥴대분류 */
	DEPT_NO NUMBER NOT NULL /* 부서코드 */
);

COMMENT ON TABLE TSCHEDULE IS '팀내스케쥴러';

COMMENT ON COLUMN TSCHEDULE.TSCH_NO IS '팀내 스케쥴번호';

COMMENT ON COLUMN TSCHEDULE.TSCH_TITLE IS '팀내 스케쥴제목';

COMMENT ON COLUMN TSCHEDULE.TSCH_START IS '팀내 스케쥴시작날짜';

COMMENT ON COLUMN TSCHEDULE.TSCH_END IS '팀내 스케쥴끝날짜';

COMMENT ON COLUMN TSCHEDULE.TSCH_CONTENT IS '팀내 스케쥴내용';

COMMENT ON COLUMN TSCHEDULE.TSCH_CATEG IS '팀내 스케쥴대분류';

COMMENT ON COLUMN TSCHEDULE.DEPT_NO IS '부서코드';

CREATE UNIQUE INDEX PK_TSCHEDULE
	ON TSCHEDULE (
		TSCH_NO ASC
	);

ALTER TABLE TSCHEDULE
	ADD
		CONSTRAINT PK_TSCHEDULE
		PRIMARY KEY (
			TSCH_NO
		);

/* 근태관리 */
CREATE TABLE COMMUTE (
	CMT_NO NUMBER NOT NULL, /* 근태관리번호 */
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	CMT_IN TIMESTAMP NOT NULL, /* 출근시간 */
	CMT_OUT TIMESTAMP NOT NULL, /* 퇴근시간 */
	CMT_STATUS VARCHAR2(50) NOT NULL /* 근태상태 */
);

COMMENT ON TABLE COMMUTE IS '근태관리';

COMMENT ON COLUMN COMMUTE.CMT_NO IS '근태관리번호';

COMMENT ON COLUMN COMMUTE.EMP_NO IS '사원번호';

COMMENT ON COLUMN COMMUTE.CMT_IN IS '출근시간';

COMMENT ON COLUMN COMMUTE.CMT_OUT IS '퇴근시간';

COMMENT ON COLUMN COMMUTE.CMT_STATUS IS '근태상태';

CREATE UNIQUE INDEX PK_COMMUTE
	ON COMMUTE (
		CMT_NO ASC
	);

ALTER TABLE COMMUTE
	ADD
		CONSTRAINT PK_COMMUTE
		PRIMARY KEY (
			CMT_NO
		);

/* 전자결재 */
CREATE TABLE CONFIRM (
	CF_NO VARCHAR(100) NOT NULL, /* 문서번호 */
	FORM_NO NUMBER NOT NULL, /* 양식번호 */
	EMP_NO NUMBER NOT NULL, /* 기안자 */
	CF_REGDATE TIMESTAMP DEFAULT sysdate, /* 기안일자 */
	LINK_CF_NO VARCHAR(100), /* 연계문서번호 */
	CF_TITLE VARCHAR(100) NOT NULL, /* 기안제목 */
	CF_CONTENT CLOB NOT NULL, /* 기안내용 */
	CF_ISFILE VARCHAR(10), /* 파일여부 */
	CF_STATUS VARCHAR(50) NOT NULL /* 현재상태 */
);

COMMENT ON TABLE CONFIRM IS '전자결재';

COMMENT ON COLUMN CONFIRM.CF_NO IS '문서번호';

COMMENT ON COLUMN CONFIRM.FORM_NO IS '양식번호';

COMMENT ON COLUMN CONFIRM.EMP_NO IS '기안자';

COMMENT ON COLUMN CONFIRM.CF_REGDATE IS '기안일자';

COMMENT ON COLUMN CONFIRM.LINK_CF_NO IS '연계문서번호';

COMMENT ON COLUMN CONFIRM.CF_TITLE IS '기안제목';

COMMENT ON COLUMN CONFIRM.CF_CONTENT IS '기안내용';

COMMENT ON COLUMN CONFIRM.CF_ISFILE IS '파일여부';

COMMENT ON COLUMN CONFIRM.CF_STATUS IS '현재상태';

CREATE UNIQUE INDEX PK_CONFIRM
	ON CONFIRM (
		CF_NO ASC
	);

ALTER TABLE CONFIRM
	ADD
		CONSTRAINT PK_CONFIRM
		PRIMARY KEY (
			CF_NO
		);

/* 첨부파일 */
CREATE TABLE CONFIRM_FILE (
	FILE_NO NUMBER NOT NULL, /* 파일번호 */
	FILE_NAME VARCHAR(100) NOT NULL, /* 파일이름 */
	FILE_ORI_NAME VARCHAR(100) NOT NULL, /* 원래파일이름 */
	FILE_SIZE VARCHAR(100) NOT NULL, /* 파일용량 */
	CF_NO VARCHAR(100) NOT NULL /* 문서번호 */
);

COMMENT ON TABLE CONFIRM_FILE IS '첨부파일';

COMMENT ON COLUMN CONFIRM_FILE.FILE_NO IS '파일번호';

COMMENT ON COLUMN CONFIRM_FILE.FILE_NAME IS '파일이름';

COMMENT ON COLUMN CONFIRM_FILE.FILE_ORI_NAME IS '원래파일이름';

COMMENT ON COLUMN CONFIRM_FILE.FILE_SIZE IS '파일용량';

COMMENT ON COLUMN CONFIRM_FILE.CF_NO IS '문서번호';

CREATE UNIQUE INDEX PK_CONFIRM_FILE
	ON CONFIRM_FILE (
		FILE_NO ASC
	);

ALTER TABLE CONFIRM_FILE
	ADD
		CONSTRAINT PK_CONFIRM_FILE
		PRIMARY KEY (
			FILE_NO
		);

/* 결재라인등록 */
CREATE TABLE SAVE_LINE (
	SAVE_NO NUMBER NOT NULL, /* 등록번호 */
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	SAVE_NAME VARCHAR(100), /* 등록이름 */
	SAVE_CONFIRMER VARCHAR(300) NOT NULL /* 결재자 */
);

COMMENT ON TABLE SAVE_LINE IS '결재라인등록';

COMMENT ON COLUMN SAVE_LINE.SAVE_NO IS '등록번호';

COMMENT ON COLUMN SAVE_LINE.EMP_NO IS '사원번호';

COMMENT ON COLUMN SAVE_LINE.SAVE_NAME IS '등록이름';

COMMENT ON COLUMN SAVE_LINE.SAVE_CONFIRMER IS '결재자';

CREATE UNIQUE INDEX PK_SAVE_LINE
	ON SAVE_LINE (
		SAVE_NO ASC
	);

ALTER TABLE SAVE_LINE
	ADD
		CONSTRAINT PK_SAVE_LINE
		PRIMARY KEY (
			SAVE_NO
		);

/* 결재서명등록 */
CREATE TABLE SIGN (
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	SIGN_NAME VARCHAR(100), /* 파일이름 */
	SIGN_ORI_NAME VARCHAR(100), /* 원래파일이름 */
	SIGN_SIZE VARCHAR(100) /* 파일용량 */
);

COMMENT ON TABLE SIGN IS '결재서명등록';

COMMENT ON COLUMN SIGN.EMP_NO IS '사원번호';

COMMENT ON COLUMN SIGN.SIGN_NAME IS '파일이름';

COMMENT ON COLUMN SIGN.SIGN_ORI_NAME IS '원래파일이름';

COMMENT ON COLUMN SIGN.SIGN_SIZE IS '파일용량';

CREATE UNIQUE INDEX PK_SIGN
	ON SIGN (
		EMP_NO ASC
	);

ALTER TABLE SIGN
	ADD
		CONSTRAINT PK_SIGN
		PRIMARY KEY (
			EMP_NO
		);

/* 의견 */
CREATE TABLE COMM (
	COMM_NO NUMBER NOT NULL, /* 의견번호 */
	MEM_NO NUMBER NOT NULL, /* 사원번호 */
	COMM_REGDATE TIMESTAMP DEFAULT sysdate, /* 작성일 */
	COMM_CONTENT CLOB NOT NULL, /* 내용 */
	CF_NO VARCHAR(100) NOT NULL /* 문서번호 */
);

COMMENT ON TABLE COMM IS '의견';

COMMENT ON COLUMN COMM.COMM_NO IS '의견번호';

COMMENT ON COLUMN COMM.MEM_NO IS '사원번호';

COMMENT ON COLUMN COMM.COMM_REGDATE IS '작성일';

COMMENT ON COLUMN COMM.COMM_CONTENT IS '내용';

COMMENT ON COLUMN COMM.CF_NO IS '문서번호';

CREATE UNIQUE INDEX PK_COMM
	ON COMM (
		COMM_NO ASC
	);

ALTER TABLE COMM
	ADD
		CONSTRAINT PK_COMM
		PRIMARY KEY (
			COMM_NO
		);

/* 문서양식 */
CREATE TABLE DOC_FORM (
	FORM_NO NUMBER NOT NULL, /* 양식번호 */
	FORM_NAME VARCHAR2(100) NOT NULL, /* 양식이름 */
	FORM_TYPE_NO NUMBER NOT NULL, /* 문서종류번호 */
	FORM_SECU VARCHAR2(50), /* 보안수준 */
	FORM_LIFE VARCHAR2(10), /* 보존년한 */
	FORM_EX VARCHAR2(500) /* 설명 */
);

COMMENT ON TABLE DOC_FORM IS '문서양식';

COMMENT ON COLUMN DOC_FORM.FORM_NO IS '양식번호';

COMMENT ON COLUMN DOC_FORM.FORM_NAME IS '양식이름';

COMMENT ON COLUMN DOC_FORM.FORM_TYPE_NO IS '문서종류번호';

COMMENT ON COLUMN DOC_FORM.FORM_SECU IS '보안수준';

COMMENT ON COLUMN DOC_FORM.FORM_LIFE IS '보존년한';

COMMENT ON COLUMN DOC_FORM.FORM_EX IS '설명';

CREATE UNIQUE INDEX PK_DOC_FORM
	ON DOC_FORM (
		FORM_NO ASC
	);

ALTER TABLE DOC_FORM
	ADD
		CONSTRAINT PK_DOC_FORM
		PRIMARY KEY (
			FORM_NO
		);

/* 문서종류 */
CREATE TABLE DOC_TYPE (
	TYPE_NO NUMBER NOT NULL, /* 문서종류번호 */
	TYPE_TYPE VARCHAR(100) NOT NULL /* 문서종류 */
);

COMMENT ON TABLE DOC_TYPE IS '문서종류';

COMMENT ON COLUMN DOC_TYPE.TYPE_NO IS '문서종류번호';

COMMENT ON COLUMN DOC_TYPE.TYPE_TYPE IS '문서종류';

CREATE UNIQUE INDEX PK_DOC_TYPE
	ON DOC_TYPE (
		TYPE_NO ASC
	);

ALTER TABLE DOC_TYPE
	ADD
		CONSTRAINT PK_DOC_TYPE
		PRIMARY KEY (
			TYPE_NO
		);

/* 결재라인 */
CREATE TABLE CONFIRM_LINE (
	LINE_NO NUMBER NOT NULL, /* 결재라인번호 */
	EMP_NO NUMBER, /* 결재자 */
	LINE_STAT VARCHAR2(50), /* 결재상태 */
	CF_NO VARCHAR(100), /* 문서번호 */
	LINE_REGDATE TIMESTAMP DEFAULT SYSDATE /* 결재변경일자 */
);

COMMENT ON TABLE CONFIRM_LINE IS '결재라인';

COMMENT ON COLUMN CONFIRM_LINE.LINE_NO IS '결재라인번호';

COMMENT ON COLUMN CONFIRM_LINE.EMP_NO IS '결재자';

COMMENT ON COLUMN CONFIRM_LINE.LINE_STAT IS '결재상태';

COMMENT ON COLUMN CONFIRM_LINE.CF_NO IS '문서번호';

COMMENT ON COLUMN CONFIRM_LINE.LINE_REGDATE IS '결재변경일자';

CREATE UNIQUE INDEX PK_CONFIRM_LINE
	ON CONFIRM_LINE (
		LINE_NO ASC
	);

ALTER TABLE CONFIRM_LINE
	ADD
		CONSTRAINT PK_CONFIRM_LINE
		PRIMARY KEY (
			LINE_NO
		);

/* 주소록그룹 */
CREATE TABLE ADDGROUP (
	GROUP_NO NUMBER NOT NULL, /* 그룹번호 */
	GROUP_NAME VARCHAR2(50), /* 그룹이름 */
	ADDR_NO NUMBER /* 주소록번호 */
);

COMMENT ON TABLE ADDGROUP IS '주소록그룹';

COMMENT ON COLUMN ADDGROUP.GROUP_NO IS '그룹번호';

COMMENT ON COLUMN ADDGROUP.GROUP_NAME IS '그룹이름';

COMMENT ON COLUMN ADDGROUP.ADDR_NO IS '주소록번호';

CREATE UNIQUE INDEX PK_ADDGROUP
	ON ADDGROUP (
		GROUP_NO ASC
	);

ALTER TABLE ADDGROUP
	ADD
		CONSTRAINT PK_ADDGROUP
		PRIMARY KEY (
			GROUP_NO
		);
select * from MESSAGE_REC;
/* 받는사람 */
CREATE TABLE MESSAGE_REC (
	REC_NO NUMBER NOT NULL, /* 시퀀스 */
	MSG_READFLAG VARCHAR2(50) DEFAULT 'N', /* 읽기여부 */
	EMP_NO NUMBER NOT NULL, /* 받는회원번호 */
	MSG_NO NUMBER NOT NULL /* 쪽지번호 */
);

COMMENT ON TABLE MESSAGE_REC IS '받는사람';

COMMENT ON COLUMN MESSAGE_REC.REC_NO IS '시퀀스';

COMMENT ON COLUMN MESSAGE_REC.MSG_READFLAG IS '읽기여부';

COMMENT ON COLUMN MESSAGE_REC.EMP_NO IS '받는회원번호';

COMMENT ON COLUMN MESSAGE_REC.MSG_NO IS '쪽지번호';

CREATE UNIQUE INDEX PK_MESSAGE_REC
	ON MESSAGE_REC (
		REC_NO ASC
	);

ALTER TABLE MESSAGE_REC
	ADD
		CONSTRAINT PK_MESSAGE_REC
		PRIMARY KEY (
			REC_NO
		);

ALTER TABLE EMP
	ADD
		CONSTRAINT FK_DEPT_TO_EMP --부서 -> 사원FK
		FOREIGN KEY (
			DEPT_NO
		)
		REFERENCES DEPT (
			DEPT_NO
		);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_EMP_TO_NOTICE -- 사원 -> 공지사항FK
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE RESOURCEREG -- 사원 -> 자원관리FK
	ADD
		CONSTRAINT FK_EMP_TO_RESOURCEREG
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE WEBHARD -- 사원 -> 웹하드FK
	ADD
		CONSTRAINT FK_EMP_TO_WEBHARD
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE MESSAGE -- 사원 -> 쪽지FK
	ADD
		CONSTRAINT FK_EMP_TO_MESSAGE2
		FOREIGN KEY (
			SENDEMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE NEWS -- 사원 -> 사내뉴스FK
	ADD
		CONSTRAINT FK_EMP_TO_NEWS
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE NEWS_COM -- 사원 -> 사내뉴스 답변FK
	ADD
		CONSTRAINT FK_EMP_TO_NEWS_COM
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE NEWS_COM -- 사내뉴스 -> 사내뉴스 답변FK
	ADD
		CONSTRAINT FK_NEWS_TO_NEWS_COM
		FOREIGN KEY (
			NEWS_NO
		)
		REFERENCES NEWS (
			NEWS_NO
		);

ALTER TABLE ADDRBOOK -- 사원 -> 주소록FK => 사원을 지우면 주소록 삭제
	ADD
		CONSTRAINT FK_EMP_TO_ADDRBOOK
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		) ON DELETE CASCADE;

ALTER TABLE PSCHEDULE -- 사원 -> 개인스케쥴러FK
	ADD
		CONSTRAINT FK_EMP_TO_PSCHEDULE
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE RESERVATION --사원 -> 자원예약FK => 사원 삭제시 자원예약 삭제
	ADD
		CONSTRAINT FK_EMP_TO_RESERVATION
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		) ON DELETE CASCADE;

ALTER TABLE RESERVATION -- 자원관리 -> 자원예약FK => 자원 삭제시 예약도 삭제
	ADD
		CONSTRAINT FK_RESOURCEREG_TO_RESERVATION
		FOREIGN KEY (
			RES_NO
		)
		REFERENCES RESOURCEREG (
			RES_NO
		) ON DELETE CASCADE;

ALTER TABLE TSCHEDULE -- 부서 -> 팀내스케쥴러FK =>부서 삭제시 팀내 스케쥴도 삭제
	ADD
		CONSTRAINT FK_DEPT_TO_TSCHEDULE
		FOREIGN KEY (
			DEPT_NO
		)
		REFERENCES DEPT (
			DEPT_NO
		) ON DELETE CASCADE;

ALTER TABLE COMMUTE -- 사원 -> 근태관리FK
	ADD
		CONSTRAINT FK_EMP_TO_COMMUTE
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE CONFIRM -- 전자결재 -> 전자결재FK (연계문서 링크)
	ADD
		CONSTRAINT FK_CONFIRM_TO_CONFIRM
		FOREIGN KEY (
			LINK_CF_NO
		)
		REFERENCES CONFIRM (
			CF_NO
		);

ALTER TABLE CONFIRM -- 사원 -> 전자결재FK
	ADD
		CONSTRAINT FK_EMP_TO_CONFIRM
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE CONFIRM -- 문서양식 -> 전자결재FK
	ADD
		CONSTRAINT FK_DOC_FORM_TO_CONFIRM
		FOREIGN KEY (
			FORM_NO
		)
		REFERENCES DOC_FORM (
			FORM_NO
		);

ALTER TABLE CONFIRM_FILE -- 전자결재 -> 첨부파일FK => 결재문서 삭제시 첨부파일 삭제
	ADD
		CONSTRAINT FK_CONFIRM_TO_CONFIRM_FILE
		FOREIGN KEY (
			CF_NO
		)
		REFERENCES CONFIRM (
			CF_NO
		) ON DELETE CASCADE;

ALTER TABLE SAVE_LINE -- 사원 -> 결재라인등록FK =>사원 삭제시 첨부파일 삭제
	ADD
		CONSTRAINT FK_EMP_TO_SAVE_LINE
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		) ON DELETE CASCADE;

ALTER TABLE SIGN -- 사원 -> 결재사인등록FK => 사원 삭제시 결재사인파일 삭제
	ADD
		CONSTRAINT FK_EMP_TO_SIGN
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		) ON DELETE CASCADE;

ALTER TABLE COMM -- 전자결재 -> 의견FK => 결재문서 삭제시 의견(코멘트 삭제)
	ADD
		CONSTRAINT FK_CONFIRM_TO_COMM
		FOREIGN KEY (
			CF_NO
		)
		REFERENCES CONFIRM (
			CF_NO
		) ON DELETE CASCADE;

ALTER TABLE COMM -- 사원 -> 의견FK => 사원삭제시 의견(코멘트) 삭제
	ADD
		CONSTRAINT FK_EMP_TO_COMM
		FOREIGN KEY (
			MEM_NO
		)
		REFERENCES EMP (
			EMP_NO
		) ON DELETE CASCADE;

ALTER TABLE DOC_FORM -- 문서종류 - 문서양식FK =>결재문서종류 삭제시 문서양식 삭제
	ADD
		CONSTRAINT FK_DOC_TYPE_TO_DOC_FORM
		FOREIGN KEY (
			FORM_TYPE_NO
		)
		REFERENCES DOC_TYPE (
			TYPE_NO
		) ON DELETE CASCADE;

ALTER TABLE CONFIRM_LINE -- 사원 - 결재라인FK
	ADD
		CONSTRAINT FK_EMP_TO_CONFIRM_LINE
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		);

ALTER TABLE CONFIRM_LINE -- 전자결재 -> 결재라인FK => 결재문서 삭제시 결재라인 삭제
	ADD
		CONSTRAINT FK_CONFIRM_TO_CONFIRM_LINE
		FOREIGN KEY (
			CF_NO
		)
		REFERENCES CONFIRM (
			CF_NO
		) ON DELETE CASCADE;

ALTER TABLE ADDGROUP -- 주소록 -> 주소록그룹FK
	ADD
		CONSTRAINT FK_ADDRBOOK_TO_ADDGROUP
		FOREIGN KEY (
			ADDR_NO
		)
		REFERENCES ADDRBOOK (
			ADDR_NO
		);

ALTER TABLE MESSAGE_REC -- 사원 -> 받는사람FK => 사원 삭제시 받는사람 삭제
	ADD
		CONSTRAINT FK_EMP_TO_MESSAGE_REC
		FOREIGN KEY (
			EMP_NO
		)
		REFERENCES EMP (
			EMP_NO
		) ON DELETE CASCADE;

ALTER TABLE MESSAGE_REC -- 쪽지 -> 받는사람FK => 쪽지 삭제시 받는사람 삭제
	ADD
		CONSTRAINT FK_MESSAGE_TO_MESSAGE_REC
		FOREIGN KEY (
			MSG_NO
		)
		REFERENCES MESSAGE (
			MSG_NO
		) ON DELETE CASCADE;